export const geners = [
    { name: "Blues", id: "Blues" },
    { name: "Jazz", id: "Jazz" },
    { name: "Pop", id: "Pop" },
    { name: "Rock n Roll", id: "Rock n Roll" },
    { name: "Punk", id: "Punk" },
    { name: "Contemporary", id: "Contemporary" },
    { name: "Rap", id: "Rap" },
    { name: "Trance", id: "Trance" },
    { name: "Drum n Bass", id: "Drum n Bass" },
    { name: "Country", id: "Country" },
    { name: "Industrial", id: "Industrial" },
    { name: "Down Tempo", id: "Down Tempo" },
    { name: "Techno", id: "Techno" },
    { name: "Rythm n Blues", id: "Rythm n Blues" },
    { name: "Wave", id: "Wave" },
    { name: "Hardcore", id: "Hardcore" },
    { name: "Breakbeat", id: "Breakbeat" },
    { name: "Open Mic", id: "Open Mic" },
    { name: "Hip Hop", id: "Hip Hop" },
    { name: "Electronic", id: "Electronic" },
  ];