export const GET_SUPER_GENRES_REQUEST = 'GET_SUPER_GENRES_REQUEST';
export const GET_SUPER_GENRES_SUCCESS = 'GET_SUPER_GENRES_SUCCESS';
export const GET_SUPER_GENRES_FAILURE = 'GET_SUPER_GENRES_FAILURE';

export const GET_CITY_SUGGESTIONS_REQUEST = 'GET_CITY_SUGGESTIONS_REQUEST';
export const GET_CITY_SUGGESTIONS_SUCCESS = 'GET_CITY_SUGGESTIONS_SUCCESS';
export const GET_CITY_SUGGESTIONS_FAILURE = 'GET_CITY_SUGGESTIONS_FAILURE';

export const VALIDATE_COMMUNITY_REQUEST = 'VALIDATE_COMMUNITY_REQUEST';
export const VALIDATE_COMMUNITY_SUCCESS = 'VALIDATE_COMMUNITY_SUCCESS';
export const VALIDATE_COMMUNITY_FAILURE = 'VALIDATE_COMMUNITY_FAILURE';

export const FINALIZE_ONBOARDING_REQUEST = 'FINALIZE_ONBOARDING_REQUEST';
export const FINALIZE_ONBOARDING_SUCCESS = 'FINALIZE_ONBOARDING_SUCCESS';
export const FINALIZE_ONBOARDING_FAILURE = 'FINALIZE_ONBOARDING_FAILURE'; 